[package]
name = "bandit-type-inference"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
bandit-parser.workspace = true
derive_more.workspace = true
slotmap.workspace = true
