[package]
name = "bandit-type-inference"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
derive_more.workspace = true
slotmap.workspace = true

[dev-dependencies]
goldenfile.workspace = true
