[package]
name = "bandit-type-inference"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
slotmap.workspace = true
pretty.workspace = true

[dev-dependencies]
goldenfile.workspace = true
